toc:
  - name: Intro
    file: introduction.md
  - 'rondinif/phytojs'
  - name: Config
    file: configuration.md
    children:
      - config
      - DEFAULT_IS_UNDER_TEST
  - name: Logging
    file: logging.md
    children:
      - logconfig
      - DEFAULT_IS_LOG_VERBOSE
      - DEFAULT_IS_LOG_SILENT
  - name: Licence
    file: ../LICENSE
